### ISSUE TITLE
[WATERCOLOR] Visuals and Issues With Misc.

### ISSUE THREAD

**Issue by dominichayesferen** [B00merang-Project/Windows-Whistler#1]
@Elbullazul I've decided to start this in order to donate some help with the Cinnamon and Metacity of Whistler, and also to then be able to help out on the Visuals of Watercolor:

Firstly, I'll drop a link to a video by Windows On Windows about one of the main Whistler builds pre-Luna so you can get a taste of the colour scheme, etc of Watercolor:
https://www.youtube.com/watch?v=cDwfm4tfkAY

Secondly, there's an issue with the screenshot of Watercolor on your site, it's the wrong version! Here's what the correct one looks like:
http://www.intelliadmin.com/images/WaterColor_Large.jpg

**Comment by Elbullazul** [comment]
good idea feren :)

i'll push the current work, then we can get started on sync development

**Comment by Elbullazul** [comment]
working xp-like icon pack:
http://b00merang.weebly.com/icon-themes.html
https://github.com/Elbullazul/WinXP-Icons

**Comment by dominichayesferen** [comment]
@Elbullazul Longhorn Icon Set on the list?

**Comment by dominichayesferen** [comment]
@Elbullazul Also, you may want to actually base it off of Classic instead of 3.1...

**Comment by Elbullazul** [comment]
advacing pretty good:
![screenshot_2016-10-19_17-52-44](https://cloud.githubusercontent.com/assets/15310985/19540122/4fa9b804-962b-11e6-886b-f6529cc11e39.png)

**Comment by Elbullazul** [comment]
Release Candidate pushed to the repo :smiley:

**Comment by Elbullazul** [comment]
![screenshot_2016-10-20_11-13-11](https://cloud.githubusercontent.com/assets/15310985/19565988/cfb53696-96b6-11e6-8d76-09bb73502999.png)

**Comment by dominichayesferen** [comment]
@Elbullazul No offense, but in later builds, that Start Menu had a watercolor BG in it...

**Comment by Elbullazul** [comment]
like this?

![screenshot_2016-10-20_17-03-01](https://cloud.githubusercontent.com/assets/15310985/19577869/15019d54-96e7-11e6-8ea5-45d8fa00e82d.png)

**Comment by dominichayesferen** [comment]
Yeah, and white text on the blue part
(You did that)

**Comment by dominichayesferen** [comment]
@Elbullazul You may want to update the screenshot to show the text as white for StarkMenu... It means the difference between someone getting it or not for some people.

**Comment by Elbullazul** [comment]
![screenshot_2016-10-24_14-36-56](https://cloud.githubusercontent.com/assets/15310985/19658801/5f7d3740-99f7-11e6-9112-67ba533dfb71.png)

**Comment by dominichayesferen** [comment]
Also, maybe use Classic95 as the icon set, remember, in Whistler, it was a mixture of 2000 and XP icons at first pre-luna

**Comment by dominichayesferen** [comment]
...maybe update the preview on the front page?

**Comment by Elbullazul** [comment]
any other suggestions before we move from the RC phase?

**Comment by dominichayesferen** [comment]
@Elbullazul Maybe a (baby) Luna variant? (apart from that, not sure)
